before_script:
    - apt-get update -qq && apt-get install -y -qq rename
    
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - rm ./public/index.html
    - mv ./public/local.html ./public/index.html
    - mkdir ./public/works ./public/works/kyushu
  artifacts:
    expire_in: 6 mos
    paths:
      - public
  only:
    - main
